# Generated by Django 3.2.6 on 2022-07-09 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_book_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='tb_book_info',
            name='book_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='书籍id'),
        ),
        migrations.AlterField(
            model_name='tb_book_info',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 23, 20, 16, 165059), verbose_name='创建时间'),
        ),
    ]
