# Generated by Django 3.2.6 on 2022-07-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220709_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_book_info',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tb_book_info',
            name='store',
            field=models.CharField(max_length=50, verbose_name='所属商店'),
        ),
        migrations.AlterField(
            model_name='tb_book_info',
            name='title',
            field=models.CharField(max_length=50, verbose_name='书籍名称'),
        ),
    ]
