# Generated by Django 3.2.6 on 2022-07-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220710_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_book_info',
            name='publish_id',
            field=models.CharField(max_length=100, null=True, verbose_name='出版社id'),
        ),
        migrations.AlterField(
            model_name='tb_book_info',
            name='num',
            field=models.IntegerField(verbose_name='库存'),
        ),
    ]
