# Generated by Django 3.2.6 on 2022-07-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220710_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_book_info',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
    ]
